# Generated by Django 4.2 on 2023-10-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_student_student_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students',
            new_name='teachers',
        ),
    ]
